name: main

on:
  push:
    branches:
      - "main"
    tags-ignore:
      - "**"

permissions:
  actions: write
  checks: write
  contents: write
  statuses: write
  deployments: write

env:
  NODE_ENV: production
  CLOUDFLARE_ENV: production
  FORCE_COLOR: true
  DO_NOT_TRACK: "1"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checks:
    uses: ./.github/workflows/checks.yaml
    secrets: inherit

  release:
    name: 📦 release
    uses: ./.github/workflows/release.yaml
    if: "github.repository_owner == 'likec4' && contains(github.event.head_commit.message, 'chore: release')"
    needs: checks
    secrets: inherit

  vscode:
    name: 📦 vscode
    uses: ./.github/workflows/vscode.yaml
    if: "github.repository_owner == 'likec4' && contains(github.event.head_commit.message, 'chore: release')"
    needs: checks
    secrets: inherit

  deploy-playground:
    if: ${{ github.repository_owner == 'likec4' }}
    needs: checks
    name: deploy
    uses: ./.github/workflows/playground.yaml
    secrets: inherit
    with:
      environment: "${{ contains(github.event.head_commit.message, 'chore: release') && 'production' || 'preview' }}"

  deploy-docs:
    if: ${{ github.repository_owner == 'likec4' }}
    needs: checks
    name: deploy
    uses: ./.github/workflows/docs.yaml
    secrets: inherit
    with:
      environment: "${{ contains(github.event.head_commit.message, 'chore: release') && 'production' || 'preview' }}"
